'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class TextFormField

	'''<summary>
	'''LabelControl control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LabelControl As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''InputHiddenIdDado control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents InputHiddenIdDado As Global.System.Web.UI.HtmlControls.HtmlInputHidden

	'''<summary>
	'''TextBoxControl control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents TextBoxControl As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''CustomValidator control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents CustomValidator As Global.System.Web.UI.WebControls.CustomValidator
End Class
