'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class VisualizarVendas

	'''<summary>
	'''ListsagemVendasPanel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ListsagemVendasPanel As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''VendasTituloMedio control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents VendasTituloMedio As Global.WebEcommerceGabriel.TituloMedio

	'''<summary>
	'''VendasGW control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents VendasGW As Global.System.Web.UI.WebControls.GridView

	'''<summary>
	'''TotalLabel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents TotalLabel As Global.System.Web.UI.WebControls.Label
End Class
