'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class VisualizarDetalhesVenda

	'''<summary>
	'''DetalhesVendaTituloMedio control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents DetalhesVendaTituloMedio As Global.WebEcommerceGabriel.TituloMedio

	'''<summary>
	'''NumeroVendaLabel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents NumeroVendaLabel As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''DataVendaLabel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents DataVendaLabel As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''ClienteLabel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ClienteLabel As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''ItensVendaGW control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ItensVendaGW As Global.System.Web.UI.WebControls.GridView

	'''<summary>
	'''VoltarButton control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents VoltarButton As Global.System.Web.UI.WebControls.Button
End Class
