'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SiteMaster

	'''<summary>
	'''Head control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Head As Global.System.Web.UI.WebControls.ContentPlaceHolder

	'''<summary>
	'''MainContent control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents MainContent As Global.System.Web.UI.WebControls.ContentPlaceHolder

	'''<summary>
	'''MasterPageToast control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents MasterPageToast As Global.WebEcommerceGabriel.Toast

	'''<summary>
	'''MasterPageModalConfirmacaoExclusao control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents MasterPageModalConfirmacaoExclusao As Global.WebEcommerceGabriel.ModalConfirmacaoExclusao

	'''<summary>
	'''PageScripts control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents PageScripts As Global.System.Web.UI.WebControls.ContentPlaceHolder
End Class
