'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class RegistroVenda

	'''<summary>
	'''RegistroVendaPanel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents RegistroVendaPanel As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''RegistroVendaTituloMedio control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents RegistroVendaTituloMedio As Global.WebEcommerceGabriel.TituloMedio

	'''<summary>
	'''NomeClienteTextFormField control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents NomeClienteTextFormField As Global.WebEcommerceGabriel.TextFormField

	'''<summary>
	'''ProdutosDropDownList control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ProdutosDropDownList As Global.WebEcommerceGabriel.GPDropDownList

	'''<summary>
	'''InserirItemButton control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents InserirItemButton As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''QuantidadeTextFormField control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents QuantidadeTextFormField As Global.WebEcommerceGabriel.TextFormField

	'''<summary>
	'''PrecoUnitTextFormField control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents PrecoUnitTextFormField As Global.WebEcommerceGabriel.TextFormField

	'''<summary>
	'''OKButton control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents OKButton As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''GerarVendaButton control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents GerarVendaButton As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''ItensVendaGW control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ItensVendaGW As Global.System.Web.UI.WebControls.GridView

	'''<summary>
	'''TotalVendaLabel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents TotalVendaLabel As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''VoltarButton control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents VoltarButton As Global.System.Web.UI.WebControls.Button
End Class
