'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CadastroProduto

	'''<summary>
	'''FormAddEditProdutoPanel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents FormAddEditProdutoPanel As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''FormAddEditProdutoTituloMedio control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents FormAddEditProdutoTituloMedio As Global.System.Web.UI.UserControl

	'''<summary>
	'''DescricaoTextFormField control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents DescricaoTextFormField As Global.System.Web.UI.UserControl

	'''<summary>
	'''VlrUnitarioTextFormField control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents VlrUnitarioTextFormField As Global.System.Web.UI.UserControl

	'''<summary>
	'''CancelarButton control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents CancelarButton As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''SalvarButton control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents SalvarButton As Global.System.Web.UI.WebControls.Button
End Class
