'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CadastroProduto

	'''<summary>
	'''FormAddEditProdutoPanel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents FormAddEditProdutoPanel As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''FormAddEditProdutoTituloMedio control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents FormAddEditProdutoTituloMedio As Global.WebEcommerceGabriel.TituloMedio

	'''<summary>
	'''CodTextFormField control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents CodTextFormField As Global.WebEcommerceGabriel.TextFormField

	'''<summary>
	'''BuscarButton control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents BuscarButton As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''DescricaoTextFormField control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents DescricaoTextFormField As Global.WebEcommerceGabriel.TextFormField

	'''<summary>
	'''PrecoUnitTextFormField control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents PrecoUnitTextFormField As Global.WebEcommerceGabriel.TextFormField

	'''<summary>
	'''SaldoEstoqueTextFormField control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents SaldoEstoqueTextFormField As Global.WebEcommerceGabriel.TextFormField

	'''<summary>
	'''CancelarButton control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents CancelarButton As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''SalvarButton control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents SalvarButton As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''VoltarButton control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents VoltarButton As Global.System.Web.UI.WebControls.Button
End Class
